### ISSUE TITLE
PULFA Export Task should not run in Staging.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3462]
This occurred two Mondays in a row. 

[Figgy/production] TypeError: no implicit conversion of nil into String

https://github.com/pulibrary/figgy/blob/master/app/services/pulfa_exporter/svn_client.rb#L27

## Backtrace

    line 27 of [PROJECT_ROOT]/app/services/pulfa_exporter/svn_client.rb: join
    line 27 of [PROJECT_ROOT]/app/services/pulfa_exporter/svn_client.rb: svn_dir
    line 11 of [PROJECT_ROOT]/app/services/pulfa_exporter/svn_client.rb: initialize

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/56124815)

Also this honeybadger error:
https://app.honeybadger.io/projects/53391/faults/56397571

**Comment by tpendragon** [comment]
Should be resolved.

**Comment by tpendragon** [comment]
This is still happening.

**Comment by tpendragon** [comment]
This is only happening in staging.

**Comment by christinach** [comment]
This is still happening.

**Comment by eliotjordan** [comment]
This is still an issue. Deploying to staging still adds the pulfa export cron job.
